kakao:
  clientId: fb026f43b3bb840254305153927af4c2
  redirectUri: http://www.potenfinance.site:8080/api/auth/kakao/callback
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
spring:
  datasource:
    url: jdbc:mysql://223.130.157.148:3306/subit?useSSL=false&serverTimezone=UTC
    username: poten412
    password: poten412!
    driver-class-name: com.mysql.cj.jdbc.Driver